"""add updated_at to players

Revision ID: 7cc6b1814833
Revises: db59f730c5c1
Create Date: 2026-06-09 17:26:28.572226

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7cc6b1814833"
down_revision: Union[str, Sequence[str], None] = "db59f730c5c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "players",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_index(op.f("ix_players_updated_at"), "players", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_updated_at"), table_name="players")
    op.drop_column("players", "updated_at")
    # ### end Alembic commands ###
