"""Create match_players table

Revision ID: 32e960817110
Revises: a7c262ca8f84
Create Date: 2026-02-01 16:28:39.290611

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "32e960817110"
down_revision: Union[str, Sequence[str], None] = "a7c262ca8f84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_players",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("membership", sa.String(), nullable=False),
        sa.Column("game_player_id", sa.BigInteger(), nullable=False),
        sa.Column("game_player_name", sa.String(), nullable=True),
        sa.Column("game_skill_level", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_players_game_player_id"), "match_players", ["game_player_id"], unique=False
    )
    op.create_index(
        op.f("ix_match_players_membership"), "match_players", ["membership"], unique=False
    )
    op.create_index(
        op.f("ix_match_players_player_id"), "match_players", ["player_id"], unique=False
    )
    op.drop_index(op.f("ix_matches_maps"), table_name="matches")
    op.drop_column("teams", "roster")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column(
            "roster", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
    )
    op.create_index(op.f("ix_matches_maps"), "matches", ["maps"], unique=False)
    op.drop_index(op.f("ix_match_players_player_id"), table_name="match_players")
    op.drop_index(op.f("ix_match_players_membership"), table_name="match_players")
    op.drop_index(op.f("ix_match_players_game_player_id"), table_name="match_players")
    op.drop_table("match_players")
    # ### end Alembic commands ###
