"""add database indexes for performance optimization

Revision ID: 2013d39dd549
Revises: 2d4d5a8c0cbe
Create Date: 2026-01-31 16:44:08.173303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2013d39dd549"
down_revision: Union[str, Sequence[str], None] = "2d4d5a8c0cbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_matches_calculate_elo"),
        "matches",
        ["calculate_elo"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matches_competition_id"),
        "matches",
        ["competition_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matches_competition_type"),
        "matches",
        ["competition_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matches_finished_at"),
        "matches",
        ["finished_at"],
        unique=False,
    )
    op.create_index(op.f("ix_matches_map"), "matches", ["map"], unique=False)
    op.create_index(
        op.f("ix_matches_organizer_id"),
        "matches",
        ["organizer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_matches_region"), "matches", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_matches_started_at"), "matches", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_matches_status"), "matches", ["status"], unique=False
    )
    op.drop_constraint(op.f("players_nickname_key"), "players", type_="unique")
    op.create_index(
        op.f("ix_players_activated_at"),
        "players",
        ["activated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_country"), "players", ["country"], unique=False
    )
    op.create_index(
        op.f("ix_players_faceit_elo"), "players", ["faceit_elo"], unique=False
    )
    op.create_index(
        op.f("ix_players_nickname"), "players", ["nickname"], unique=True
    )
    op.create_index(
        op.f("ix_players_region"), "players", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_players_skill_level"),
        "players",
        ["skill_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_players_steam_id_64"),
        "players",
        ["steam_id_64"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_steam_id_64"), table_name="players")
    op.drop_index(op.f("ix_players_skill_level"), table_name="players")
    op.drop_index(op.f("ix_players_region"), table_name="players")
    op.drop_index(op.f("ix_players_nickname"), table_name="players")
    op.drop_index(op.f("ix_players_faceit_elo"), table_name="players")
    op.drop_index(op.f("ix_players_country"), table_name="players")
    op.drop_index(op.f("ix_players_activated_at"), table_name="players")
    op.create_unique_constraint(
        op.f("players_nickname_key"),
        "players",
        ["nickname"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_matches_status"), table_name="matches")
    op.drop_index(op.f("ix_matches_started_at"), table_name="matches")
    op.drop_index(op.f("ix_matches_region"), table_name="matches")
    op.drop_index(op.f("ix_matches_organizer_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_map"), table_name="matches")
    op.drop_index(op.f("ix_matches_finished_at"), table_name="matches")
    op.drop_index(op.f("ix_matches_competition_type"), table_name="matches")
    op.drop_index(op.f("ix_matches_competition_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_calculate_elo"), table_name="matches")
    # ### end Alembic commands ###
