"""rename match table and update default values

Revision ID: 2d4d5a8c0cbe
Revises: 9efb8781d8b6
Create Date: 2026-01-30 21:01:44.210682

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d4d5a8c0cbe"
down_revision: Union[str, Sequence[str], None] = "9efb8781d8b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matches",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("competition_id", sa.String(), nullable=False),
        sa.Column("competition_type", sa.String(), nullable=False),
        sa.Column("competition_name", sa.String(), nullable=False),
        sa.Column("organizer_id", sa.String(), nullable=False),
        sa.Column("teams", sa.JSON(), nullable=False),
        sa.Column("map", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("winner", sa.String(), nullable=False),
        sa.Column("score", sa.JSON(), nullable=False),
        sa.Column("configured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("best_of", sa.Integer(), nullable=False),
        sa.Column(
            "calculate_elo",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
        sa.Column("faceit_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    op.drop_table("matchs")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchs",
        sa.Column(
            "match_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "competition_type",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "competition_name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "organizer_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "teams",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "configured_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "best_of", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "results",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "faceit_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "voting",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("match_id", name=op.f("matchs_pkey")),
    )
    op.drop_table("matches")
    # ### end Alembic commands ###
