"""change maps column type to ARRAY(String) in Match model

Revision ID: e81ad960f76e
Revises: 2013d39dd549
Create Date: 2026-02-01 10:22:13.311989

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e81ad960f76e"
down_revision: Union[str, Sequence[str], None] = "2013d39dd549"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches", sa.Column("maps", sa.ARRAY(sa.String()), server_default="{}", nullable=False)
    )
    op.drop_index(op.f("ix_matches_map"), table_name="matches")
    op.create_index(op.f("ix_matches_maps"), "matches", ["maps"], unique=False)
    op.drop_column("matches", "map")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("map", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f("ix_matches_maps"), table_name="matches")
    op.create_index(op.f("ix_matches_map"), "matches", ["map"], unique=False)
    op.drop_column("matches", "maps")
    # ### end Alembic commands ###
