"""Create map_stats table

Revision ID: 8d29a3998409
Revises: 32e960817110
Create Date: 2026-02-04 18:05:54.084739

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8d29a3998409"
down_revision: Union[str, Sequence[str], None] = "32e960817110"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map_stats",
        sa.Column("map_name", sa.String(), nullable=False),
        sa.Column("matches", sa.Integer(), nullable=False),
        sa.Column("won", sa.Integer(), nullable=False),
        sa.Column("lost", sa.Integer(), nullable=False),
        sa.Column("winrate", sa.Float(), nullable=False),
        sa.Column("average_kills", sa.Float(), nullable=False),
        sa.Column("average_deaths", sa.Float(), nullable=False),
        sa.Column("average_kd_ratio", sa.Float(), nullable=False),
        sa.Column("average_kr_ratio", sa.Float(), nullable=False),
        sa.Column("hs", sa.Float(), nullable=False),
        sa.Column("adr", sa.Float(), nullable=False),
        sa.Column("rounds", sa.Integer(), nullable=False),
        sa.Column("kills", sa.Integer(), nullable=False),
        sa.Column("assists", sa.Integer(), nullable=False),
        sa.Column("deaths", sa.Integer(), nullable=False),
        sa.Column("headshots", sa.Integer(), nullable=False),
        sa.Column("total_damage", sa.Integer(), nullable=False),
        sa.Column("penta_kills", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.player_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "map_name", name="uq_player_map_stats"),
    )
    op.create_index(op.f("ix_map_stats_player_id"), "map_stats", ["player_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_map_stats_player_id"), table_name="map_stats")
    op.drop_table("map_stats")
    # ### end Alembic commands ###
