"""Create match table

Revision ID: 9efb8781d8b6
Revises: eb87d03ce3cc
Create Date: 2026-01-30 19:37:38.319578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9efb8781d8b6"
down_revision: Union[str, Sequence[str], None] = "eb87d03ce3cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "matchs",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("competition_type", sa.String(), nullable=False),
        sa.Column("competition_name", sa.String(), nullable=False),
        sa.Column("organizer_id", sa.String(), nullable=False),
        sa.Column("teams", sa.JSON(), nullable=False),
        sa.Column("configured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("best_of", sa.Integer(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("faceit_url", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("match_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matchs")
    # ### end Alembic commands ###
