"""Create player table

Revision ID: b16e3dc8d96a
Revises:
Create Date: 2026-01-30 01:06:53.878767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b16e3dc8d96a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "players",
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column(
            "verified",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("steam_nickname", sa.String(), nullable=True),
        sa.Column("steam_id_64", sa.BigInteger(), nullable=False),
        sa.Column("faceit_url", sa.String(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column(
            "friends_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("activated_at", sa.DateTime(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("skill_level", sa.Integer(), nullable=False),
        sa.Column("faceit_elo", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("player_id"),
        sa.UniqueConstraint("nickname"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("players")
    # ### end Alembic commands ###
