"""Create team table

Revision ID: a7c262ca8f84
Revises: e81ad960f76e
Create Date: 2026-02-01 13:07:56.182657

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a7c262ca8f84"
down_revision: Union[str, Sequence[str], None] = "e81ad960f76e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("faction_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("roster", sa.JSON(), nullable=False),
        sa.Column("win_probability", sa.Float(), nullable=True),
        sa.Column("average_skill_level", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["match_id"], ["matches.match_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_faction_id"), "teams", ["faction_id"], unique=False)
    op.drop_column("matches", "teams")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column(
            "teams", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_teams_faction_id"), table_name="teams")
    op.drop_table("teams")
    # ### end Alembic commands ###
