"""add player_stats table

Revision ID: 74d113f81164
Revises: 7cc6b1814833
Create Date: 2026-06-26 16:00:11.117911

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "74d113f81164"
down_revision: Union[str, Sequence[str], None] = "7cc6b1814833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_stats",
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("matches_analyzed", sa.Integer(), nullable=False),
        sa.Column("winrate", sa.Float(), nullable=False),
        sa.Column("avg_kills", sa.Float(), nullable=False),
        sa.Column("avg_deaths", sa.Float(), nullable=False),
        sa.Column("avg_assists", sa.Float(), nullable=False),
        sa.Column("avg_damage", sa.Float(), nullable=False),
        sa.Column("kd_ratio", sa.Float(), nullable=False),
        sa.Column("kr_ratio", sa.Float(), nullable=False),
        sa.Column("headshots_percent", sa.Float(), nullable=False),
        sa.Column("adr", sa.Float(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.player_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("player_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("player_stats")
    # ### end Alembic commands ###
