"""set_composite_pk_for_player_match_history

Revision ID: cba6c624a835
Revises: 7cc6b1814833
Create Date: 2026-06-14 19:19:07.107161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cba6c624a835"
down_revision: Union[str, Sequence[str], None] = "7cc6b1814833"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_match_history",
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("finished_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_win", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.player_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_id", "match_id"),
    )
    op.create_index(
        "ix_player_match_history_player_time",
        "player_match_history",
        ["player_id", "finished_at_utc"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_match_history_player_time", table_name="player_match_history")
    op.drop_table("player_match_history")
    # ### end Alembic commands ###
