"""Add player match history cache.

Revision ID: c8896a148f3f
Revises: 8d29a3998409
Create Date: 2026-02-12 21:45:25.695052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "c8896a148f3f"
down_revision: Union[str, Sequence[str], None] = "8d29a3998409"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_match_history",
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("match_id", sa.String(), nullable=False),
        sa.Column("finished_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_win", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["players.player_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "match_id", name="uq_player_match_history"),
    )
    op.create_index(
        "ix_player_match_history_player_time",
        "player_match_history",
        ["player_id", "finished_at_utc"],
        unique=False,
    )
    op.add_column(
        "players", sa.Column("match_history_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_players_match_history_updated_at"),
        "players",
        ["match_history_updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_players_match_history_updated_at"), table_name="players")
    op.drop_column("players", "match_history_updated_at")
    op.drop_index("ix_player_match_history_player_time", table_name="player_match_history")
    op.drop_table("player_match_history")
    # ### end Alembic commands ###
